### ISSUE TITLE
Please update the stable version of flup-py3 on pypi

### ISSUE THREAD

**Issue by yookoala** [pquentin/flup-py3#1]
As you'd have known, the version flup-py3-1.0.2-1 doesn't work on Python 3. You have to at least use f657c54 to get it work. Is there anything stopping the package to use the development version as the stable one? Is there anything that blocks pypi from updating?

**Comment by pquentin** [comment]
@yookoala Thanks for the report, but I don't own flup-py3 on PyPI. Sorry.

(And I don't use flup-py3 anymore, because I now use WSGI.)

**Comment by yookoala** [comment]
Understood. Thanks for replying.
